# Generated by Django 5.0.6 on 2024-05-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('stars', models.IntegerField()),
                ('forks', models.IntegerField()),
            ],
        ),
    ]
